### ISSUE TITLE
Move over Shuffle 

### ISSUE THREAD

**Issue by mrocklin** [dask-contrib/dask-expr#10]
So far we've migrated two pieces of sizable functionality

-  Apply-concat-apply
-  Read_parquet

The next chunk I think it would be good to move over is shuffling.

It would also be nice if we could simplify things as we move them over.  In at least the ACA case (the only one I have real knowledge of) the code got significantly simpler (my guess is 25% the original size).  My hope is that we could do something similar with shuffling as well.

**Comment by mrocklin** [comment]
@rjzamora I'm not sure what you're excited about next, but from my perspective this would be a good candidate

**Comment by rjzamora** [comment]
Yes - I'll attack this next.

**Related thought**: Perhaps we should use P0-P2 labels to coordinate/agree on the highest priority items? Or maybe allow priority discussion/rationalization in a "meta" issue?

**Comment by mrocklin** [comment]
🤷‍♂️ happy either way.  Right now there aren't that many issues, and there
aren't that many of us, so I'm inclined to continue handling this ad-hoc.
If labels would help you though then I'm game to do that.

**Comment by rjzamora** [comment]
All three shuffle routines ("tasks", "disk", "p2p") have been ported at this point.
