### ISSUE TITLE
Fallback to `dask.dataframe` methods 

### ISSUE THREAD

**Issue by jrbourbeau** [dask-contrib/dask-expr#122]
We're working to fill out the DataFrame API here. Several important operations work, but there's still a lot of API surface not covered. One option would be to fall back to the existing `dask.dataframe` implementation when a `dask-expr` method doesn't exist. 

This is just one possible option. I don't think we should focus on this at this stage. Just logging the idea.

**Comment by phofl** [comment]
We now cover most of the api and fall back in some places as appropriate
