### ISSUE TITLE
Move to dask-contrib?

### ISSUE THREAD

**Issue by mrocklin** [dask-contrib/dask-expr#143]
Maybe it's time for this to stop living in my personal github account

**Comment by rjzamora** [comment]
+1

**Comment by mrocklin** [comment]
Pinging @jacobtomlinson so that he's aware.  Moving end of day my time if no one else beats me to it.

**Comment by jacobtomlinson** [comment]
Sounds great!

**Comment by mrocklin** [comment]
Done.
