### ISSUE TITLE
Benchmark failures - bugs/missing operations

### ISSUE THREAD

**Issue by phofl** [dask-contrib/dask-expr#159]
- [x] GroupBy.value_counts
- [ ] iloc
- [x] select_dtypes
- [x] Repartition misses keyword-argument ``partition_size``
- [ ] GroupBy.apply
- [x] ``set_index``
- [x] grouping by a Series object
- [ ] grouping by an Index object
- [x] ``assign`` with callable
- [ ] ``GroupBy.agg`` ``shuffle`` keyword
- [x] missing align step in add/sub, ...
- [x] missing keywords in ``read_csv``
- [x] "p2p" shuffle

Not planning on fixing all of them immediately, just collecting failures and fixing what was on my agenda anyway or is a very small fix.

Reference build: https://github.com/coiled/benchmarks/actions/runs/5310108176/jobs/9611644148?pr=837

**Comment by phofl** [comment]
@mrocklin thoughts on ``partition_size`` in ``repartition``? This triggers an immediate computation in dask/dask, but I think we could reasonably defer this to compute time

**Comment by mrocklin** [comment]
I think that anything we can defer we should defer.  

I think that for this value in particular we'll likely have to compute it if anything asks us for divisions.

**Comment by phofl** [comment]
closing, those all work
