### ISSUE TITLE
[Proposal] Add "phases" argument to `Expr.simplify`

### ISSUE THREAD

**Issue by rjzamora** [dask-contrib/dask-expr#194]
I spent some time thinking about #166, #181 and #186 yesterday, and experimented a bit with optimization ordering. I played with  some relatively complex approaches, but ultimately decided to propose something pretty simple.

**General Idea**: We add an optional `phases: tuple` argument to `simplify`, move the graph-traversal logic into a `_simplify` method, and add an `allow_group` argument to `_simplify`, `_simplify_up`, and `simplify_down`.

**Rough Code Outline**:

```python
class AbstractExpr(Expr):
    # "Example" Expr class
    
    _simplified = None  # Use attribute for hashing (can be done in separate work)

    def _simpify_down(self, allow_group: tuple):
        # Hypothetical example
        if "repartition" in allow_group:
            # Hold off on "lowering" until "repartition" phase
            return RepartitionDivisions(...)
    
    def _simpify_up(self, parent, allow_group: tuple):
        # Probably don't need to check allow_group for projection
        if isinstance(parent, Projection):
            ...
                
def simplify(self, phases=("abstract", "lower", "repartition")):
    # NOTE: Could always add/change phases later on
    
    # Loop over all "phases"
    expr = self
    for p in range(len(phases)):
        allow_group = phases[:p+1]
        
        # For each phase, we do the usual "simplify" loop
        # calling _simplify_down, _simplify_up and _simplify
        # until nothing changes. We pass in `allow_group`
        # to enforce rough ordering of optimizations.
        ...
        
    return expr

def _simplify(self, allow_group: tuple):
    
    # Use chached result if available
    if (self._simplified or {}).get(allow_group) is not None:
        return self._simplified
    
    # Usual "simplify" loop here, but `allow_group`
    # is passed to `_simplify_up` and `_simplify_down`
    expr = self
    ...
    
    # Cache result
    self._simplified = {allow_group: expr}
    return expr
```

**Comment by rjzamora** [comment]
@phofl - This certainly overlaps with #193

Note that one of my earlier experiments did something like `simplify().lower()`, but I remembered discussing with @mrocklin a while back that we will probably end up wanting more than two simplify-like "phases" in the long run. Also, we will probably want to run the more-general simplify optimizations *after* lowering as well.

**Comment by phofl** [comment]
Yes I think that I agree with you. This became more and more obvious while I was playing with the ``lower`` implementation. Mentioned something similar in #192 as well. 

Running the general simplify optimisations again is very helpful as well, not doing this concerned me a bit in the lower implementation, even though I wasn't able to produce any concrete bugs. 

Do you intend to put up a PR with this version?

**Comment by rjzamora** [comment]
>Do you intend to put up a PR with this version?

Yes, I can do this today if you agree with the general approach. Also feel free to suggest tweaks to the idea if any come to mind :)

**Comment by phofl** [comment]
I am a bit concerned that we might run expensive steps (steps that trigger computations, like set_index) more than once. But this is something that we don't have to completely think through right now.

The approach sounds good to me.

**Comment by mrocklin** [comment]
There have been a few proposals for this floating around.  Do we have a plan on how to handle this short-term?  If not I can think about this more.  Mostly I'm curious if we're blocked.

**Comment by phofl** [comment]
I was planning on updating #192 today so that we can work with an explicit simplify and an explicit lower layer for now.

**Comment by rjzamora** [comment]
Closing this as it is now slightly stale.
