### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by mrocklin** [dask-contrib/dask-expr#225]
I think that @phofl plans to do an initial release today.  Mostly raising this issue so that @rjzamora is aware (going ahead without waiting for approval though).

**Comment by rjzamora** [comment]
Sounds good, thanks @mrocklin.

As I mentioned to @phofl offline, my only suggestion is to update the readme to clarify the experimental nature of the API.

**Comment by phofl** [comment]
release is out

https://pypi.org/project/dask-expr/0.1.0/#description

**Comment by phofl** [comment]
I added both of you to the pypi project. Closing here
