### ISSUE TITLE
Add API-coverage documentation

### ISSUE THREAD

**Issue by rjzamora** [dask-contrib/dask-expr#234]
Motivated by https://github.com/dask-contrib/dask-expr/issues/233

We need a space to document the available API coverage, and to leave notes about current limitations.

**Comment by phofl** [comment]
Do you propose rendering proper docs or just a readme or something like this?

**Comment by rjzamora** [comment]
>Do you propose rendering proper docs or just a readme or something like this?

I think it would be fine to add this information to the README  in the short term. Once someone has time to set up a proper doc framework, we can move the information into a dedicated/rendered page. Wdyt?

**Comment by phofl** [comment]
Yeah that sounds good.

**Comment by rjzamora** [comment]
>Yeah that sounds good.

I threw up #235 in the short term, but I certainly welcome other (better) solutions :)
