### ISSUE TITLE
Optimizing Filters and Merges

### ISSUE THREAD

**Issue by mrocklin** [dask-contrib/dask-expr#302]
I was writing down some tests to help me think through swapping filters and merges

```python
def test_filter_merge():
    a = pd.DataFrame({"a": range(5), "b": range(5), "c": range(5)})
    b = pd.DataFrame({"c": [0, 2, 4, 6, 8], "x": range(5), "y": range(5)})

    a = dx.from_pandas(a)
    b = dx.from_pandas(b)

    # Some simple cases
    df = a.merge(b)
    df = df[df.x > 3]
    bb = b[b.x > 3]
    expected = a.merge(bb)
    assert df.optimize()._name == expected.optimize()._name

    df = a.merge(b)
    df = df[df.b > 3]
    aa = a[a.b > 3]
    expected = aa.merge(b)
    assert df.optimize()._name == expected.optimize()._name

    # Apply to both!
    df = a.merge(b)
    df = df[df.c > 3]
    aa = a[a.c > 3]
    bb = b[b.c > 3]
    expected = aa.merge(bb)
    assert df.optimize()._name == expected.optimize()._name

    # Works with more complex expressions, and multiple columns
    df = a.merge(b)
    df = df[df.a > df.b + 1]
    aa = a[a.a > a.b + 1]
    expected = aa.merge(b)
    assert df.optimize()._name == expected.optimize()._name

    # Only apply if all columns are in the table, not if only some are
    df = a.merge(b)
    df = df[df.c > df.x + 1]
    bb = b[b.c > b.x + 1]
    expected = a.merge(bb)
    assert df.optimize()._name == expected.optimize()._name

    # Bail if we engage non-elemwise expressions in the predicates
    df = a.merge(b)
    df = df[df.x > df.y.sum()]
    bb = b[b.x > b.y.sum()]
    not_expected = a.merge(bb)
    assert df.optimize()._name != not_expected.optimize()._name
```

I think that what I came to is that we want to push a filter into one side or the other if

1.   the predicate is valid when we replace the merged table with the left or right side.  Something like if `predicate.subs({merged: left})` doesn't raise an error (after we figure out renaming of columns).
2. The predicate has only elemwise expressions (nothing like `df.x < df.y.sum()` for example)

And so maybe an implementation here relies on ...

1.  Making a proxy object for `left` that has no expression history, but does have the same `._meta`
2. Calling `substitute` and seeing if it errs
3. Scanning through the substituted predicate expression and seeing if everything in it is `Elemwise`

I think that that should cover most cases and be various robust.  

Things get a bit more complex if we also want to support `And` clauses (there are cases where we could split a predicate into two parts and each part applies to one side) but I think that this is probably pretty rare and not important.

I don't plan to do this work, but it was interesting to think through.  I suspect that at some point we'll run into this problem, either in a benchmark or in practice and in that case I hope that the tests and discussion above help a little.

**Comment by hendrikmakait** [comment]
> I suspect that at some point we'll run into this problem, either in a benchmark or in practice and in that case I hope that the tests and discussion above help a little.

@milesgranger and I ran into this when working on the remaining TPC-H queries.

> Things get a bit more complex if we also want to support And clauses (there are cases where we could split a predicate into two parts and each part applies to one side) but I think that this is probably pretty rare and not important.

FWIW, we've had to deal with multiple of these cases and needed to manually optimize in order for queries to work.

**Comment by mrocklin** [comment]
Well I'm glad I wrote up these thoughts several months ago.  I hope that they become useful (but no worries if another approach ends up being more helpful).

**Comment by phofl** [comment]
This should work now
