### ISSUE TITLE
Replace dask.dataframe

### ISSUE THREAD

**Issue by mrocklin** [dask-contrib/dask-expr#374]
At some point `import dask.dataframe` should point here.  When should that happen?

### Broadly 

One answer to this question is "once dask-expr fully supports the existing dask.dataframe API".  I think that I reject that answer (not that anyone is giving it).  

Another answer is "once we'd recommend a new user use dask-expr over using dask.dataframe, being aware of the limitations of each".  This is also probably something to reject because it discounts the surprise of existing users.

Probably the answer is some blend, when dask-expr is "better enough" that it makes sense to surprise people a little.  

### Specifically

What are the major API points that we should address before moving?  

What are explicit non-goals?

Is there anything we should be doing now to smooth the way?

**Comment by mrocklin** [comment]
> Probably the answer is some blend, when dask-expr is "better enough" that it makes sense to surprise people a little.

Building on this, I think that the blend depends on how much we care about current users (avoiding churn) vs how much we care about new users (growth).  I'm inclined to be pretty growth-oriented, which would encourage us to make the move pretty early.

**Comment by jrbourbeau** [comment]
> Is there anything we should be doing now to smooth the way?

Having an off-by-default config option in `dask/dask` that swaps out `dask.dataframe` for `dask-expr` seems like a good initial step with low (no?) risk

**Comment by phofl** [comment]
dask-expr is the default in dask/dask, so closing
