### ISSUE TITLE
Dask DataFrame has many functions that are not only defined on the df but also given as functions

### ISSUE THREAD

**Issue by phofl** [dask-contrib/dask-expr#396]
``to_parquet``, ``merge``, ...

We only define them on the collection.

Should we add them as functions as well? Makes sense to increase compatibility

**Comment by mrocklin** [comment]
> Should we add them as functions as well?

My usual answer to questions is "we should do what pandas does"

**Comment by phofl** [comment]
I decided to make them available if it makes sense
