### ISSUE TITLE
Running into RecursionError: maximum recursion depth exceeded 

### ISSUE THREAD

**Issue by aimran-adroll** [dask-contrib/dask-expr#402]
Running a fairly simple workload to test out the expr. But quickly ran into a RecursionError issue

I can not share data but the code is following. I have ran it on coiled as well as on my laptop

```python
pdf_raw = dd.read_parquet(
    files,  # list of 100 parquet files on s3
    columns=["cid, "pid", "pg", "pa"],
)   


pdf_raw = pdf_raw.rename(columns={"pid": "product_id"})
pdf_raw = pdf_raw.fillna(value={"pg":"", "pa":""})
pdf_raw = pdf_raw[pdf_raw.pa.isin(['','YWRkdG9jYXJ0','cHVyY2hhc2Vk'])]

pdf_raw = pdf_raw.set_index("cid")

pdf_raw.head()
```

It begins by taking forever to "think". At least with regular dask, you can see task stream marching with each partitions to know its loading data etc.

In any case, almost within 5 seconds, it fails here

```
File ~/Code/python/revealwise/.venv/lib/python3.10/site-packages/pandas/core/dtypes/generic.py:38, in create_pandas_abc_type.<locals>._check(inst)
     37 def _check(inst) -> bool:
---> 38     return getattr(inst, attr, "_typ") in comp

RecursionError: maximum recursion depth exceeded while calling a Python object
```

My System details:  I have ran it on coiled as well as on my laptop

```
Python version       : 3.10.13
IPython version      : 8.17.2

Compiler    : Clang 16.0.3 
OS          : Darwin
Release     : 22.6.0
Machine     : arm64
Processor   : arm
CPU cores   : 8
Architecture: 64bit


s3fs     : 2023.10.0
pandas   : 2.1.3
numpy    : 1.26.2
coiled   : 1.1.14
dask     : 2023.11.0
dask_expr: 0.2.0
```

**Comment by phofl** [comment]
Thx for the report. We are a little susceptible to recursions still because a few things aren't supported yet, I will take a look

**Comment by phofl** [comment]
I was able to fix the issue (is already on main)

I pushed out a release to pypi, conda-forge will follow after their bots pick up the release 

A note regarding it takes a little to load: We do a bunch of optimisations before we start running actual code, your reproducer failed during the optimization step, that's why you can't see anything on the dask dashboard

**Comment by aimran-adroll** [comment]
Thanks Patrick for the ⚡ response!

Confirming that RecursionError is gone. 

>A note regarding it takes a little to load: We do a bunch of optimisations before we start running actual code, your reproducer failed during the optimization step, that's why you can't see anything on the dask dashboard

At least locally, I see that it has created something called a `readparquet_fused_chunks` and number of tasks has dropped by a lot. But I am assuming its reading in larger number of files at a time so the experience is a touch jarring perhaps.

Do you recommend any graph that might be useful to stare at whilst its thinking.  

Thanks again for the speedy fix

**Comment by mrocklin** [comment]
> Do you recommend any graph that might be useful to stare at whilst its thinking.

I'd expect thinking time to be sub-second at this stage for any reasonably sized query.  Do you experience something different?

**Comment by phofl** [comment]
It might be a little longer since we access the parquet file to get the columns. But not much longer if the internet connection is stable.

How many different files are you accessing? 

> At least locally, I see that it has created something called a readparquet_fused_chunks and number of tasks has dropped by a lot. But I am assuming its reading in larger number of files at a time so the experience is a touch jarring perhaps.

Previously, dask looked at the size of one file to figure out if one file should be a single partition in the Dask DataFrame. This didn't take dropped columns into account, which means that you could end up with tiny partitions if you only read a very small number of columns from the file. dask-expr takes the ration from columns to dropped columns into account and fuses different files together to avoid these issues

**Comment by aimran-adroll** [comment]
Hey All 👋🏽 

first off ... this is not super pressing. I am embarrassed that I am bugging you about this.

Please take it as very minor feedback on ux. Matt is right that the thinking is sub-second. But now there maybe some additional optimization that is happening whereby it fuses all the reading in one step. Instead of seeing _many_ tiny little read tasks on the graph, it seems to be doing the reading in one go. Might be purely psychological  

See the little video to see what I mean. BTW, I am using 100 s3 files here. The work begins at 17:39:20 and ends at ~17:39:52 and no discernible visual indication of work (other than

https://recordit.co/Ovr3VeZHOs

**Comment by mrocklin** [comment]
Looks like it's small enough that it was all put into a single partition,
and so we lost parallelism.  Probably we should be sensitive to this case
and not fuse too aggressively.

Asif, thanks for being sensitive to what is urgent and non-urgent.  I
encourage you not to worry about over saturating us.  We're both quite
experienced at ignoring users when appropriate.  Dask-expr is at a state
where lots of micro-feedback is useful.

**Comment by aimran-adroll** [comment]
>Can you tell us the ratio of total number of columns to the number of columns you extracted from the file?

~ 50:1  (hey, we all have tech debts we are not proud of ;-)

>Could you check what the number of partitions of pdf_raw is after the persist?, e.g. pdf_raw.npartitions will tell you that

Its been reduced to 1! This part is super super-surprising since I have been trying to use set-index after our phone convo. There should be at least 96 customer-ids (my index col). When I use vanilla dask.dataframe, I get 96

**Comment by rjzamora** [comment]
>~ 50:1 

Yeah, it seems like the io-fusion factor will indeed try to reduce the number of partitions by a lot for a case like this. This is a good data point for us to have right now.

**Comment by phofl** [comment]
Yes this is very helpful!

This gets us a lot closer to the single task we are seeing. I'd have expected 2 tasks though. Any chance that the optimiser was able to drop another couple of columns because they aren't used? I guess not, but want to be sure.

I think a good solution is to make the fusion factor dependent on the total number of partitions and adjust if we are fusing to agressively

**Comment by aimran-adroll** [comment]
> Any chance that the optimiser was able to drop another couple of columns because they aren't used? I guess not, but want to be sure.

Nope. (In fact, I just noticed that I hand wrote the `columns` filter in the read_parquet) 


Lovely! Happy to provide more data points if necessary. But glad to hear things are making sense to the experts.

I will try with lot (lot) more files next to see if it does anything different

**Comment by mrocklin** [comment]
Fine by me.  My guess is that in the future we'll want to be sensitive to the number of threads, but I'm happy to defer that to when it occurs.

**Comment by phofl** [comment]
I agree but we don't have access to this information at the moment

**Comment by phofl** [comment]
@aimran-adroll 

I've pushed another release to pypi (0.2.2) that should give you 10 tasks instead of 1 if you want to give it a try.
