### ISSUE TITLE
Dask allows instantiating a DataFrame directly

### ISSUE THREAD

**Issue by phofl** [dask-contrib/dask-expr#502]
Dask allows something like ``dd.DataFrame(...)`` where the first argument is the actual Dask graph. This seems counterintuitive for us, so we should probably not support this in the future?

cc @mrocklin

**Comment by mrocklin** [comment]
I think of this as being mostly developer-focused API.  I'm fine to not
support it in public API.  I think I probably care less about
public/private separation than you do.

**Comment by phofl** [comment]
I agree that we shouldn't support this, closing
