### ISSUE TITLE
Dask exposes aca and reduction as user accessible methods

### ISSUE THREAD

**Issue by phofl** [dask-contrib/dask-expr#544]
Should we do the same? Haven't thought through a potential interface yet,

cc @mrocklin

**Comment by mrocklin** [comment]
I honestly don't care much about public/private.  I'm pretty comfortable
exposing and removing things.  My sense is that you're more careful than I
am :)

**Comment by phofl** [comment]
Sorry, I was trying to go into a little bit of a different direction. We don't have such a method at all at the moment, I am curious if it's worth the effort to implement or just not bother with it until someone complains with a valid use case

**Comment by fjetter** [comment]
While this is not an exact science, there is apparently not a single public github repo that is using `apply_concat_apply`, see https://github.com/search?q=%22apply_concat_apply%22+NOT+%22def+apply_concat_apply%22+language%3APython+NOT+path%3Adask%2F**%2F*.py&type=code
and all hits I find for `aca` are from `dask_cudf` 

https://github.com/rapidsai/cudf/blob/cee642916cfc3b8df73e819bf3bc50f1b9fc684f/python/dask_cudf/dask_cudf/groupby.py#L613

https://github.com/search?q=%22+aca%28%22+NOT+%22def+apply_concat_apply%22+language%3APython+NOT+path%3Adask%2F**%2F*.py&type=code&p=1

I guess a library like cudf needs the possibility to use this

Haven't done the same for reduction but I guess the exercise plays our similarly.

**Comment by phofl** [comment]
Thx! I didn't consider that search path. CuDF can simply inherit from the ApplyConcatApply expression, so this isn't needed for now, closing
