### ISSUE TITLE
GroupBy Aggregation with split_out > 1 ignores split_every

### ISSUE THREAD

**Issue by phofl** [dask-contrib/dask-expr#597]
This seems odd and might lead to huge chunks, cc @rjzamora I think you added this initially, do you have time to take a look?

**Comment by rjzamora** [comment]
Thanks for the ping @phofl. I assigned myself to this issue, but I'm not immediately finding evidence that we are ignoring `split_every` for shuffle-based groupby aggregations. Can you help me understand the issue a bit more? I think I'm probably just confused.

Any time we lower a grouby aggregation to a `ShuffleReduce` expression, we are *supposed* to be using [split_every to choose the `npartitions` argument to Shuffle or SortValues](https://github.com/dask-contrib/dask-expr/blob/60e4cd75368e8124fc077a8daa5e069d91a12868/dask_expr/_reductions.py#L186). My understanding is that we want to use `split_every` to choose the *allowed* reduction factor after the shuffle.

Are you saying that this logic is flawed (certainly possible), or that the `split_every` parameter is getting erased/overwritten in certain cases (also very possible)? If it's the latter, do you have an example or reproducer?

**Comment by phofl** [comment]
Yes you are correct, sorry for the confusion. I think I got confused how we are doing this, the implementation is correct.

Sorry
