### ISSUE TITLE
Implement DataFrame.random_split?

### ISSUE THREAD

**Issue by phofl** [dask-contrib/dask-expr#652]
Not sure what this is actually useful for, maybe we should just straight out deprecate?

cc @mrocklin do you know what the intention is for this method?

**Comment by mrocklin** [comment]
Probably train-test splits in machine learning

```python
train_data, test_data = df.random_split([0.9, 0.1])

mymodel.train(train_data)
score = compare(mymodel.predict(test_data), actuals)
```
