### ISSUE TITLE
Make map_overlap look back multiple partitions

### ISSUE THREAD

**Issue by phofl** [dask-contrib/dask-expr#655]
Currently ffill and bfill both fail if you have an all nan partition

e.g. ``test_bfill`` in dask/dask

**Comment by fjetter** [comment]
I think this is a duplicate of https://github.com/dask-contrib/dask-expr/issues/494 isn't it? over there you were skeptical that this was even a real use case

**Comment by phofl** [comment]
Oh correct, yeah in rolling this doesn't make much sense, but ffill and friends shouldn't emit value dependent behaviour. Closing this one in favour of the other
