### ISSUE TITLE
Add more Elemwise / Blockwise operations

### ISSUE THREAD

**Issue by mrocklin** [dask-contrib/dask-expr#68]
We have many simple operations like add, mul, assign, astype, filter, etc.. that were simple and easy to add.  This part of the codebase seems pretty stable right now.

There are probably many more operations like these we could bring over without much uncertainty.  I propose that we do this, but by having someone else do it, anyone who isn't @rjzamora and @mrocklin .  This would be a good first issue.  

Some example operations:

- [x]  round
- [x] more operators
- [x] to_timestamp
- [x] map
- [ ] ~applymap~
- [x] rename
- [x]  fillna
- [x] dropna
- [x] sample
- [x] replace
- [x] abs
- [x] align 
- [x] clip 
- [x] between
- [x] combine_first
- [x] explode
- [x] to_frame
- [x] isin

**Comment by rjzamora** [comment]
Kudos to @phofl (and the others who helped) for getting through this so quickly. Nice work!
