### ISSUE TITLE
Add more reductions

### ISSUE THREAD

**Issue by mrocklin** [dask-contrib/dask-expr#70]
This should be a good first issue for someone who isn't @rjzamora or @mrocklin .  Some not-yet-existing-but-easy-reductions

- [x] any
- [x] all
- [x] prod
- [x] idxmin/idxmax
- [x] mode
- [x] var/std (this one might get strange)
- [ ] describe_1d (this one might get strange)
- [x] nbytes
- [x] drop_duplicates / unique (this one might get strange)
- [x] value_counts
- [x] nlargest / nsmallest
- [x] memory_usage

**Comment by phofl** [comment]
Chatted with Matt about this offline, we will postpone var and describe for a bit to focus on low hanging fruit for now
