### ISSUE TITLE
Implement hashing for FileMetaData object from Arrow

### ISSUE THREAD

**Issue by phofl** [dask-contrib/dask-expr#703]
cc @rjzamora if you have thoughts

**Comment by fjetter** [comment]
This allows us to use the pyarrow filesystem or what is the background here?

**Comment by phofl** [comment]
This allows to pass a meta data file as far as I could see on a first look

**Comment by rjzamora** [comment]
Given the way dask-expr works, I'm sure it would be helpful to be able to hash a FileMetaData object. However, I'd need to think through the current code a bit to say how or how much I think it would help.

In the long run, I'd really like for us to avoid reading much parquet metadata at the expression creation/optimization level at all. Once we've sampled metadata from a single file, we can estimate how many IO tasks should be assigned to each file, and then the metadata can just be parsed at IO time (I believe this is how Spark does things). I suppose it *may* still be useful to hash the sampled FileMetaData in this case, but I'm not really sure. It also seems like we could just immediately convert the important column-chunk statistics into a custom data structure.

**Comment by milesgranger** [comment]
Closed by https://github.com/apache/arrow/pull/39781

**Comment by phofl** [comment]
Can we path this somehow on our end (only if it#s relatively simple), not everyone will be on the newest arrow version

**Comment by milesgranger** [comment]
No, I don't think that's possible. `FileMetaData` hash impl now uses Schema as part of the hash which also wasn't implemented before, that uses the [bytes returned from C++ `.ToString`](https://github.com/apache/arrow/blob/bbe59b35de33a0534fc76c9617aa4746031ce16c/python/pyarrow/_parquet.pyx#L1082) which isn't available elsewhere on `Schema`.

**Comment by milesgranger** [comment]
That is if you want the same hash in versions before this was implemented. Otherwise you can follow the same logic by something like this:

```python
In [1]: import pyarrow.parquet as pq

In [2]: meta = pq.read_metadata("../lineitem-stats-no-index.snappy.parquet")

In [3]: schema = meta.schema.to_arrow_schema()

In [4]: hash(schema)
Out[4]: -5490579018560802713

In [5]: hash((schema, meta.num_rows, meta.num_row_groups, meta.format_version, meta.serialized_size))
Out[5]: -7063026471112691577
```

https://github.com/apache/arrow/blob/bbe59b35de33a0534fc76c9617aa4746031ce16c/python/pyarrow/_parquet.pyx#L853

**Comment by phofl** [comment]
I don't care about the same hash for different arrow versions as long as the hash is deterministic on a per python interpreter basis
