### ISSUE TITLE
Try dask-expr out on dask benchmarks

### ISSUE THREAD

**Issue by mrocklin** [dask-contrib/dask-expr#72]
@jrbourbeau mentioned that it might be interesting to try dask-expr out on some of the benchmarks in https://github.com/coiled/benchmarks . 

My guess is that nothing will work yet, but that it'll highlight some low-hanging fruit to pick.

Anyone could do this.  I think that @jrbourbeau is somewhat interested, although he's also out for a bit so it might make sense for someone else to try this out.

**Comment by jrbourbeau** [comment]
Okay, a couple of updates here were needed to get things running, but there are now some legitimate failures over in https://github.com/coiled/benchmarks/pull/837 if you click on the CI builds

**Comment by rjzamora** [comment]
Thanks for pushing on this @jrbourbeau !  Seems like a reasonable way to prioritize missing API items.
