### ISSUE TITLE
We don't seem to reduce the partition count when a read parquet filter is given

### ISSUE THREAD

**Issue by phofl** [dask-contrib/dask-expr#779]
See ``test_filters`` in ``test_parquet.py`` over in dask/dask

cc @rjzamora if you have thoughts

Calling optimise does not help here

**Comment by rjzamora** [comment]
I don't see a failure when I run `DASK_DATAFRAME__QUERY_PLANNING=True py.test test_parquet.py::test_filters`. Am I looking at the wrong test? (note that my environment is a bit off, but just wanted to check before I started fresh)

**Comment by phofl** [comment]
I disabled the checks that would fail so that ci passes

There is a block


```
    if not DASK_EXPR_ENABLED:
        # TODO: this doesn't reduce the partition count
        e = dd.read_parquet(tmp_path, engine=read_engine, filters=[("x", "in", (0, 9))])
        assert e.npartitions == 2
        assert ((e.x < 2) | (e.x > 7)).all().compute()
```

in there that you have to include to see the failures. I wanted to keep the other checks over just xfailing the whole test
