### ISSUE TITLE
We don't seem to calculate divisions if ``calculate_divisions=True`` and filters are given

### ISSUE THREAD

**Issue by phofl** [dask-contrib/dask-expr#780]
See ``test_pyarrow_filter_divisions`` in dask/dask

optimise doesn't help, they are still None

cc @rjzamora if you have thoughts

**Comment by rjzamora** [comment]
I'll be happy to investigate this (and #779) - Do you have specific reproducers in mind? (I can come up with something, but just wanted to check first)

**Comment by phofl** [comment]
The test in the top post is from dask/dask and reproduces, that's something you can use
