### ISSUE TITLE
`ApplyConcatApply.should_shuffle` appears to be incorrect if `sort=True`

### ISSUE THREAD

**Issue by hendrikmakait** [dask-contrib/dask-expr#817]
https://github.com/dask-contrib/dask-expr/blob/24e4e8bc1bce4daa646e98e0f7a527bc2c1d92e8/dask_expr/_reductions.py#L450-L455

See discussion at https://github.com/dask-contrib/dask-expr/pull/766#discussion_r1465399277. TL;DR:

```python
not (not isinstance(self.split_out, bool) and self.split_out == 1 or sort)
```
is the same as
```python
not (((not isinstance(self.split_out, bool)) and (self.split_out == 1)) or sort)
```
i.e., if `sort is True`, the expression evaluates to `False`.

Since we cannot use a tree reduction if `sort=True`, this appears to be wrong.

**Comment by fjetter** [comment]
if `sort==True and split_out==1` we do not need to shuffle, do we?

**Comment by hendrikmakait** [comment]
There is a bunch of confusion in the original issue that led to misunderstandings. I've had an offline discussion with @phofl. Here are a few important notes:

The `sort` keyword sorts the group keys, not the data within the individual groups, so there's no reason not to use a tree reduction. Aggregations that require a full sort of the data (e.g., `median`), will be regarded as holistic aggregations and handled accordingly.

There is the case where `sort=True` and `split_out>1`. This is currently not supported in `dask-expr`, we just ignore one of these arguments. This feels off, instead we should raise. I'll create another issue for that.

**Comment by rjzamora** [comment]
>if sort==True and split_out==1 we do not need to shuffle, do we?

Right, if `split_out == 1`, then we don't need to shuffle. I was confused when I made my comment on #766, because I was thinking of dask/dask (which allows a tree reduction to be used when `split_out > 1`). In dask-expr, it seems like we only need to check the value of sort if we are using the "holistic" aggregation.
