### ISSUE TITLE
Error when calling ``var`` or ``std`` on the group key in a ``SeriesGroupBy``

### ISSUE THREAD

**Issue by rjzamora** [dask-contrib/dask-expr#840]
```python
import dask_expr as dd
import pandas as pd

pdf = pd.DataFrame({"a": [1, 2] * 2, "b": [0] * 4})
df = dd.from_pandas(pdf , 2)

df.groupby("a")["a"].var()
```
Traceback:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[1], line 7
      4 pdf = pd.DataFrame({"a": [1, 2] * 2, "b": [0] * 4})
      5 df = dd.from_pandas(pdf , 2)
----> 7 df.groupby("a")["a"].var()

File ~/.../dask_expr/_groupby.py:1744, in GroupBy.var(self, ddof, split_every, split_out, numeric_only, shuffle_method)
   1725 result = new_collection(
   1726     Var(
   1727         self.obj.expr,
   (...)
   1737     )
   1738 )
   1739 if (
   1740     isinstance(self.obj, Series)
   1741     or is_scalar(self._slice)
   1742     and self._slice is not None
   1743 ):
-> 1744     result = result[result.columns[0]]
   1745 return result

File /.../site-packages/pandas/core/indexes/base.py:5366, in Index.__getitem__(self, key)
   5363 if is_integer(key) or is_float(key):
   5364     # GH#44051 exclude bool, which would return a 2d ndarray
   5365     key = com.cast_scalar_indexer(key)
-> 5366     return getitem(key)
   5368 if isinstance(key, slice):
   5369     # This case is separated from the conditional above to avoid
   5370     # pessimization com.is_bool_indexer and ndim checks.
   5371     return self._getitem_slice(key)

IndexError: index 0 is out of bounds for axis 0 with size 0
```
Note that I also see the same error for `std`.

**Comment by phofl** [comment]
This doesn't work in dask/dask either and I am not really convinced that it should work, the result is kind of pointless since it will always be 0

**Comment by rjzamora** [comment]
>This doesn't work in dask/dask either and I am not really convinced that it should work, the result is kind of pointless since it will always be 0

Yeah, I agree that the calculation seems pointless. I'm not sure if this is worth fixing at all, or if it's best to raise an error when someone tries to aggregate on the grouping key.

**Comment by phofl** [comment]
Some aggregations can make kind of sense and work, it's just std and var that don't work

**Comment by rjzamora** [comment]
>Some aggregations can make kind of sense and work, it's just std and var that don't work

Yes sorry - I was talking about these aggregations specifically. (background - I raised this when I noticed a dask-cudf test was failing with query-planning turned on. It wasn't until after I raised the issue that I realized the test was quite weird anyway).
