### ISSUE TITLE
Missing parameter in `AssignAlign`

### ISSUE THREAD

**Issue by rjzamora** [dask-contrib/dask-expr#864]
As mentioned [here](https://github.com/dask-contrib/dask-expr/pull/857/files#r1484688097), #857 introduced a small regression for a certain combination of assign + project. E.g.

```python
import pandas as pd
import dask_expr as dd

pdf = pd.DataFrame({"x": [0] * 20, "y": range(20)})
df = dd.from_pandas(pdf, npartitions=2)
s = pd.Series(range(10, 30))
ds = dd.from_pandas(s, npartitions=df.npartitions)
got = df.assign(z=ds)[["y", "z"]]
got.compute()  # Produces an error
```
```
AttributeError: 'AssignAlign' object has no attribute 'keys'
```

**Comment by phofl** [comment]
Yeah I missed this, wanted to rewrite it anyway... I'll take care of it

**Comment by rjzamora** [comment]
>Yeah I missed this, wanted to rewrite it anyway... I'll take care of it

Cool - Thanks @phofl !  I was hesitant to fix myself, since I had a feeling you were planning overlapping changes anyway.
