### ISSUE TITLE
Make uber-lyft example work

### ISSUE THREAD

**Issue by mrocklin** [dask-contrib/dask-expr#92]
I (and others) often use this example when giving Dask dataframe examples: https://github.com/coiled/examples/blob/main/uber-lyft.ipynb

I tried running it and, to my surprise, some things actually worked!  Not everything though, in particular:

-  value_counts doesn't exist
- Groupby aggregations like `df.groupby("hvfhs_license_num").tipped.mean().compute()` didn't seem to work

```python-traceback
AttributeError                            Traceback (most recent call last)
Cell In[11], line 3
      1 df["tipped"] = df.tips != 0
----> 3 df.groupby("hvfhs_license_num").tipped.mean().compute()

AttributeError: 'GroupBy' object has no attribute 'tipped'
```

My thinking is that by going after common workflows like this we'll find ourselves with a good objective function to help us prioritize.

**Comment by phofl** [comment]
The notebook seems to work now. Closing here.
